layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: potato4d
  medium: @potato4d
  twitter: potato4d

topics:
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/typescript/typescript.png

  - name: I18n
    web_url: https://github.com/topics/i18n

  - name: React.js
    web_url: https://reactjs.org
    image_url: https://github.com/reactjs.png

  - name: Vue.js
    web_url: https://vuejs.org
    image_url: https://vuejs.org/images/logo.png

  - name: Nuxt.js
    web_url: https://nuxtjs.org/
    image_url: https://github.com/nuxt.png

  - name: Amazon Web Services
    web_url: https://aws.amazon.com
    image_url: https://github.com/awslabs.png

  - name: Firebase
    web_url: https://firebase.google.com
    image_url: https://github.com/firebase.png

